server:
  port: 9090
spring:
  application:
    name: redissionDemo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0 #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    timeout: 10000 #连接超时时间（毫秒）
    host: 127.0.0.1
    port: 6379
    password: #默认无密码
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.company.dao: debug
